# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf1a0ceeabb7e6a75af4bdd2171c249e820086a98eca4ccc55751f6fe71b11840db378a15f91052d881f3321adedda207dee81b00e70791349181097eeab90b9

test:
  secret_key_base: 6fd54572461f11648782d785bb862fefeaf2528b8894062e9f80891f44762ce6447bd0491475c436ee7335ea4b98a68b12a8d0798ef30ec5d8dd017afa022ef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
